Repository leapmotion/autowiring, pull requests merged in 2018-03, with the labels that each got.

#1052 Remove support for auto_prev
  Doxyfile
  devguide/Files.dox
  publicDoxyfile.conf
  src/autowiring/AutoFilterArgument.h
  src/autowiring/AutoPacket.cpp
  src/autowiring/AutoPacket.h
  src/autowiring/AutoPacketFactory.cpp
  src/autowiring/AutoPacketInternal.cpp
  src/autowiring/AutoPacketInternal.hpp
  src/autowiring/AutowiringDebug.cpp
  src/autowiring/CMakeLists.txt
  src/autowiring/DecorationDisposition.h
  src/autowiring/auto_arg.h
  src/autowiring/auto_out.h
  src/autowiring/auto_prev.h
  src/autowiring/autowiring.h
  src/autowiring/test/AutoFilterCollapseRulesTest.cpp
  src/autowiring/test/AutoFilterSequencing.cpp
  src/autowiring/test/AutoFilterTest.cpp
  src/autowiring/test/AutowiringDebugTest.cpp
Labels: performance, upkeep

#1054 Allow building with newer standards than C++11 on non-MSVC platforms
  src/autowiring/C++11/memory.h
Labels: bug

#1055 Modify code to support C++17
  contrib/autoboost/autoboost/operators.hpp
  contrib/websocketpp/websocketpp/common/memory.hpp
  contrib/websocketpp/websocketpp/utilities.hpp
  src/autowiring/test/ContextEnumeratorTest.cpp
Labels: upkeep

#1053 Bump version number to 1.1.0
  Doxyfile
  publicDoxyfile.conf
  version.cmake
Labels: bug
