Repository leapmotion/autowiring, pull requests merged in 2018-02, with the labels that each got.

#1041 Fix a warning in clang 5
  src/autowiring/auto_id.h
Labels: compatibility

#1049 Fix "Unknown compiler version" warnings on MSVC
  contrib/autoboost/autoboost/config/compiler/visualc.hpp
Labels: bug, compatibility

#1050 Update standard to fix Android 32-bit compatibility
  standard/standard-configVersion.cmake.in
Labels: bug
